Jimmy
DHGrupoFilme/PIAppFilme pull request #10
Opened 2020-03-22 18:54 UTC by Londrinho

2020-03-22 23:18 UTC, Ingsantos requested changes
Jimmy, por favor, verificar a code review.
Necessário ter atenção a nomenclatura e necessidade de cada metodo.
O código também não está buildando, o principal problema é nas dependências, você adicinou algumas importações e excluiu as que são padrão do projeto.
Além disso, foi realizado a mudança de versão de vários componentes, como SDK. Vale a reflexão da real necessidade.
Depois que corrigido esse problemas do gradle, o projeto está apresentado outros problemas mais "fáceis" de serem localizados como falta de ponto e virgula, fechamento de chaves, etc.
Recomendo que você builde o projeto e faça as devidas verificações antes de abrir um Pull Request.
Só irei fazer o merge se todos os problemas forem resolvidos e se o codigo estiver buildando na sua própria branch.
Obrigada. E conte comigo se precisar de ajuda.

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Dao.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Dao.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Dao.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Dao.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Dao.java
> +    //Método que retorna um produto especifico a partir de uma consulta usando nome como parametro
Remover todos os comentários

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Quizes.java
> +
remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Quizes.java
> +
remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Quizes.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesConverter.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesConverter.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesConverter.java
> +
remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesConverter.java
> +
remover linhas

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesConverter.java
> +
remover linhas

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesDatabase.java
> +
remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Quizes.java
> +
Essa tabela não deveria ter uma Id? Quem é o PrimaryKey?

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesConverter.java
> +
Remover linhas

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +    public Flowable<List<Quizes>> getAllProdutos(Context context){
É justificável usar o Flowable se a quantidade de itens que iremos receber não é tão grande e está num json local?

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Resposta.java
> +
remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Resposta.java
> +
Remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Resposta.java
> +
remover linha

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +    public void insereProduto(Quizes quizes, Context context){
Por que insereProduto? que Produto será inserido no quiz?
Por que fazer uma inserção no Quiz, faz sentido?
As perguntas e respostas serão escritas pelos usuário? Por que um json do app então?

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +    public void apagaProduto(Quizes produto, Context context){
Por que apagaProduto? que Produto será apagado no quiz?
Por que fazer delete no Quiz, faz sentido?
As perguntas e respostas serão deletadas pelos usuário?

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +    public Quizes retornaProdutoPorNome(String nome, Context context){
Por que retorna Produto? Que produto o sistema tem que retornar?

2020-03-22 23:18 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +    public Single<Resposta> getProdutosDoArquivo(Context context) {
Que produtos devem ser pegos? 
Quando se tá trabalhando com fonte externa de dados é uma boa prática colocar o Try Catch, pois não temos controle do que pode acontecer. Porém no caso de estamos consumindo um json próprio, faz sentido?

2020-03-23 14:39 UTC, Londrinho commented on app/src/main/java/com/example/myapplication/model/Dao.java
> +
Quando tiro essa linha dá o problema com aviso"missing package statement".

2020-03-23 14:42 UTC, Londrinho commented on app/src/main/java/com/example/myapplication/model/Dao.java
> +
Os declarações do Query não funcionam se tiro essas linhas de import.

2020-03-23 14:43 UTC, Londrinho commented on app/src/main/java/com/example/myapplication/model/Dao.java
> +
Dá problemas quando tiro essas linhas.

2020-03-23 14:48 UTC, Londrinho commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +    public Single<Resposta> getProdutosDoArquivo(Context context) {
OK. "produtos" devem ser "Quizes". Arrumei agora. O Try Catch, nunca usei. Vou ler como funciona.

2020-03-23 14:49 UTC, Londrinho commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +    public Quizes retornaProdutoPorNome(String nome, Context context){
Deve ser "Quizes". Arrumei agora.

2020-03-23 14:56 UTC, Londrinho commented on app/src/main/java/com/example/myapplication/model/QuizesRepository.java
> +    public void apagaProduto(Quizes produto, Context context){
Não pensei que fosse deletar perguntas dentro do quiz e assim como os outros atributos. Mas o usuário deletar, não quis fazer isso não.

2020-03-23 22:04 UTC, closed without merging