Leonardo/sprint4
DHGrupoFilme/PIAppFilme pull request #11
Opened 2020-03-22 19:04 UTC by LeonardoCrux

2020-03-22 21:50 UTC, Ingsantos requested changes
Leo, fico aguardando a revisão do código para o merge.

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/AdapterCartas.java
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/AdapterCartas.java
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/AdapterCartas.java
remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/AdapterCartas.java
remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/AdapterCartas.java
> +
remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/AdapterCartas.java
> +
remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/FavoritoAdapter.java
> +
remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/FavoritoAdapter.java
> +
remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/FavoritoAdapter.java
> +    private Carta cartaFavoritos;
Indentar o código

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/FavoritoAdapter.java
> +
Por favor, fazer um metodo separado para iniciar as views

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/model/Carta.java
> +
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/CartaRepository.java
> +
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/CartaRepository.java
> +
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/CartaRepository.java
> +
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/CartaRepository.java
> +
remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/data/CartaConverter.java
> +
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/data/CartaConverter.java
> +
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/data/CartaConverter.java
> +
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/data/CartaDAO.java
> +
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/data/CartaDAO.java
> +
remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/data/CartaDAO.java
> +
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/data/CartaDAO.java
> +
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/data/CartaDataBase.java
> +
remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/repository/data/CartaDataBase.java
> +
Remover  linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/view/CadastroActivity.java
> +                startActivity(new Intent(getApplicationContext(), InstrucoesActivity.class));
Alguma outra classe está iniciando a InstrucoesActivity?

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/view/FiltroActivity.java
>          checkDrama = findViewById(R.id.checkDrama);
Não poderia estar dentro do initViews?

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/view/FiltroActivity.java
>          checkFiccao = findViewById(R.id.checkFiccao);
Não poderia estar dentro do initViews?

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/view/FiltroActivity.java
> +    public void testCheckBox(){
Esse metodo não deveria retornar uma lista?

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/view/SelecaoJogo.java
> +
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/view/FiltroActivity.java
> +        if (check00.isChecked())
Um sugestão é criar um metodo, por exemplo
private List<String> estaMarcado (Checkbox check){
 List<String> itemMarcado = new ArrayList();
 if(check.isChecked()){
 itemMarcado.add(check);}

return itemMarcado;
}

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/view/TrunfoActivity.java
> +
Remover linha

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/view/TrunfoActivity.java
>          setaPerdeu = findViewById(R.id.setaPerdeu);
Não poderia estar num initViews?

2020-03-22 21:50 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/viewmodel/CartaViewModel.java
> +
Remover linha

2020-03-23 01:43 UTC, Ingsantos requested changes

2020-03-23 01:43 UTC, Ingsantos commented on app/build/generated/ap_generated_sources/debug/out/com/example/myapplication/repository/data/CartaDAO_Impl.java
> +
remover linha

2020-03-23 01:43 UTC, Ingsantos commented on app/build/generated/ap_generated_sources/debug/out/com/example/myapplication/repository/data/CartaDAO_Impl.java
> +        return "INSERT OR ABORT INTO `cartas`(`idCarta`,`popularidade`,`critica`,`orcamento`,`bilheteria`,`nomeFilme`,`ano`,`imagem`) VALUES (nullif(?, 0),?,?,?,?,?,?,?)";
Por favor, explicar esse return

2020-03-23 01:43 UTC, Ingsantos commented on app/build/generated/ap_generated_sources/debug/out/com/example/myapplication/repository/data/CartaDataBase_Impl.java
> +
Remover linha

2020-03-23 01:43 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/AdapterCartas.java
> +
remover linha

2020-03-23 01:43 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/AdapterCartas.java
> +
remover linha

2020-03-23 01:43 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/AdapterCartas.java
> +
remover linha

2020-03-23 01:43 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/AdapterCartasQuiz.java
> +
Remover linha

2020-03-23 01:43 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/AdapterCartasQuiz.java
> +
Remover linha

2020-03-23 01:43 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/adapter/AdapterCartasQuiz.java
> +
remover linha

2020-03-23 01:43 UTC, Ingsantos commented on app/src/main/java/com/example/myapplication/view/TrunfoActivity.java
>          pontosGanhou = findViewById(R.id.pontosGanhou);
Essas views não poderiam estar em um metodo separado como o initviews?

2020-03-23 02:32 UTC, LeonardoCrux commented on app/build/generated/ap_generated_sources/debug/out/com/example/myapplication/repository/data/CartaDAO_Impl.java
> +        return "INSERT OR ABORT INTO `cartas`(`idCarta`,`popularidade`,`critica`,`orcamento`,`bilheteria`,`nomeFilme`,`ano`,`imagem`) VALUES (nullif(?, 0),?,?,?,?,?,?,?)";
Acho que esse arquivo foi gerado pelo android studio, ele não está localizado em main/java

2020-03-23 14:14 UTC, Ingsantos commented on app/build/generated/ap_generated_sources/debug/out/com/example/myapplication/repository/data/CartaDAO_Impl.java
> +        return "INSERT OR ABORT INTO `cartas`(`idCarta`,`popularidade`,`critica`,`orcamento`,`bilheteria`,`nomeFilme`,`ano`,`imagem`) VALUES (nullif(?, 0),?,?,?,?,?,?,?)";
Perfeito

2020-03-23 14:15 UTC, Ingsantos approved these changes

2020-03-23 21:25 UTC, merged